name: docker-reload-example

configs:
  docker-reload.yml:
    content: |
      watchers:
        - paths:
            - file: "/watchdir/file"
          selector:
            label: "watch-category=reader"
          action: "restart"

services:
  reader:
    labels:
      watch-category: reader
    image: busybox
    volumes:
      - ./watchdir:/watchdir:ro
    stop_signal: SIGKILL
    command: >-
      sh -c '
        date;
        cat /watchdir/file;
        sleep 100;
      '

  writer:
    image: busybox
    volumes:
      - ./watchdir:/watchdir
    stop_signal: SIGKILL
    restart: no
    # output redirect (>) performs a double write which is confusing for
    # inotify. solution: use tee
    command: >-
      sh -c '
        sleep 10;
        echo writing file;
        cat /dev/urandom | head -c 20 | base64 | tee /watchdir/file;
      '

  docker-reload:
    build:
      context: ..
    configs:
      - docker-reload.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./watchdir:/watchdir:ro
    command: -log-level trace
